### ISSUE TITLE
Minecraft1.19.2modloader崩溃

### ISSUE THREAD

**Issue by BILLYx1120** [AmarokIce/ThursdayDelight#4]
...我不好说，这日志看的我一脸懵
[KFCDelight错误报告-2023-9-7_17.06.20.zip](https://github.com/AmarokIce/ThursdayDelight/files/12553415/KFCDelight.-2023-9-7_17.06.20.zip)

环境：Java17, Windows 10, PCL2, Minecraft1.19.2, forge是最新稳定版本

状况：游戏启动开始加载mod时失败，所有的modloader输出只有压缩包里面那么一行

**Comment by AmarokIce** [comment]
你的游戏启动路径里存在中文与空格，让它们从你的游戏启动路径中消失，然后再试一次。
如果你非常确定是ThursdayDelight导致了这个问题，请重新提交一份新的Issue，这份Issue将会被关闭。
